### ISSUE TITLE
发送指令，提示 error:11

### ISSUE THREAD

**Issue by deboLing** [LenhartStephan/flutter_blue_classic#7] opened 2024-10-17 11:45 UTC
用你的demo跑起来，发送指令  出现error:11

**Comment by LenhartStephan** [comment] 2024-10-17 19:44
Could you elaborate a little, what your problem is? 

Typically an Issue contains a description of how to recreate the error, what your expected behavior is and what the actual results are, some sample code that lead to the issue and/or a stacktrace or some other kind of error log.

**Comment by LenhartStephan** [comment] 2024-11-17 15:19
Hey, I'm closing this for now, because I have no real error description. Please feel free to just reopen the issue with a full error explanation.

**Closed as not planned by LenhartStephan** 2024-11-17 15:19 UTC
